---
name: Pipeline
on: [push]
jobs:
  tests:
    uses: Invoca/ruby-test-matrix-workflow/.github/workflows/ruby-test-matrix.yml@main
    with:
      pre-test-hook: "sudo apt-get install liblua5.1-0"
      test-command: "bundle exec rake"
